### ISSUE TITLE
REST endpoints for tasks

### ISSUE THREAD

**Issue by jakobpalmborg** [fungover/mmotodo#12]
Tasks:
Get one task
Get all tasks? (will there be public tasks or are all private, meaning they can only be seen by the user who created it?)
Get tasks based on other criteria like, due date, categories, users, completed/uncompleted, ...?
Create a new task
Update/Change an existing task
Delete an existing task
Get all tasks (will there be public and private tasks?):

GET /api/tasks
Get all tasks for a specifik user:

GET /api/tasks Optional Queryparam ?userId=id
Get all tasks for a specifik team:

GET /api/tasks Optional Queryparam ?teamId=id
Get a single task:

GET /api/tasks/{id}
Gets  a single task:

POST /api/tasks that accepts a JSON object with a new task
Change a task:

PUT/PATCH /api/tasks/{id} or /api/tasks/ (and the ID is included in the JSON object) that accepts a JSON object
Delete a task:

DELETE /api/tasks/{id}

**Comment by yvette809** [comment]
It looks good. I think we should add this endpoint :
GET  api/tasks/{status}

**Comment by Arash-SJPI22** [comment]
> It looks good. I think we should add this endpoint : GET api/tasks/{status}

I think
GET /api/tasks with a Queryparam ?status=status
would be better or it might conflict with /api/tasks/{id}
