### ISSUE TITLE
Additional dependencies need for Flyway to work correctly

### ISSUE THREAD

**Issue by Arash-SJPI22** [fungover/mmotodo#16]
Adding following dependencies to pom.xml will fix it:

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>9.21.0</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>

And add this line to application-dev.properties:

` spring.flyway.baseline-on-migrate=true `

**Comment by jakobpalmborg** [comment]
We included this in PR #17
