### ISSUE TITLE
A view for Tasks associated with an User

### ISSUE THREAD

**Issue by liber09** [fungover/mmotodo#21]
- [x] Create a simple design proposal in figma

![image](https://github.com/fungover/mmotodo/assets/113246195/a64e13a1-96de-4df7-b3e8-10a9ccf28acc)

Should be done using Vanilla JS

**Comment by liber09** [comment]
A first draft of a design proposal for the tasks by user view

**Comment by kappsegla** [comment]
Take a look at issue #18 and the discussion there about using a standard library like bootstrap to get the same look and feel for the whole application.
